% This is an autogenerated sample test for file langevin.m
classdef testlangevin < matlab.unittest.TestCase

    methods (Test)

        function test_langevin_is_zero_at_coercivity(testCase)
            % Specify the input(s) of
            % langevin
            tol = 1e-3;
            mu0 = 4*pi*1e-7;
            Hc = 0.8/mu0;
            a = 0.01/mu0;
            H = -Hc+tol;


            % Exercise the function langevin
            actual_L = langevin(H, Hc, a);

            testCase.verifyLessThanOrEqual(actual_L, tol);
        end
    end
end